import api from './api';

export const authApi = {
  login: (email, password) => api.post('/auth/login/', { email, password }),
  register: (data) => api.post('/auth/register/', data),
  getProfile: () => api.get('/auth/profile/'),
  updateProfile: (data) => api.put('/auth/profile/update/', data),
  changePassword: (data) => api.put('/auth/profile/change-password/', data),
  refreshToken: (refresh) => api.post('/auth/token/refresh/', { refresh }),
};

export const configApi = {
  getDisciplines: () => api.get('/config/disciplines/'),
  getDiscipline: (id) => api.get(`/config/disciplines/${id}/`),
  createDiscipline: (data) => api.post('/config/disciplines/', data),
  updateDiscipline: (id, data) => api.put(`/config/disciplines/${id}/`, data),
  deleteDiscipline: (id) => api.delete(`/config/disciplines/${id}/`),
  getSexes: () => api.get('/config/sexes/'),
  getSex: (id) => api.get(`/config/sexes/${id}/`),
  createSex: (data) => api.post('/config/sexes/', data),
  updateSex: (id, data) => api.put(`/config/sexes/${id}/`, data),
  deleteSex: (id) => api.delete(`/config/sexes/${id}/`),
  getCategories: () => api.get('/config/categories/'),
  getCategory: (id) => api.get(`/config/categories/${id}/`),
  createCategory: (data) => api.post('/config/categories/', data),
  updateCategory: (id, data) => api.put(`/config/categories/${id}/`, data),
  deleteCategory: (id) => api.delete(`/config/categories/${id}/`),
  getClassifications: () => api.get('/config/classifications/'),
  getClassification: (id) => api.get(`/config/classifications/${id}/`),
  createClassification: (data) => api.post('/config/classifications/', data),
  updateClassification: (id, data) => api.put(`/config/classifications/${id}/`, data),
  deleteClassification: (id) => api.delete(`/config/classifications/${id}/`),
  getEventTypes: () => api.get('/config/event-types/'),
  getEventType: (id) => api.get(`/config/event-types/${id}/`),
  createEventType: (data) => api.post('/config/event-types/', data),
  updateEventType: (id, data) => api.put(`/config/event-types/${id}/`, data),
  deleteEventType: (id) => api.delete(`/config/event-types/${id}/`),
};

export const tournamentApi = {
  getTournaments: (params) => api.get('/tournaments/tournaments/', { params }),
  getTournament: (id) => api.get(`/tournaments/tournaments/${id}/`),
  createTournament: (data) => api.post('/tournaments/tournaments/', data),
  updateTournament: (id, data) => api.put(`/tournaments/tournaments/${id}/`, data),
  deleteTournament: (id) => api.delete(`/tournaments/tournaments/${id}/`),
  updateStatus: (id, status) => api.patch(`/tournaments/tournaments/${id}/status/`, { status }),
  getTournamentEvents: (id) => api.get(`/tournaments/tournaments/${id}/events/`),
  getInstitutions: () => api.get('/tournaments/institutions/'),
  getAvailableInstitutions: () => api.get('/tournaments/institutions/available/'),
  setCoachInstitution: (data) => api.patch('/tournaments/coaches/my/institution/', data),
  createInstitution: (data) => api.post('/tournaments/institutions/', data),
  updateInstitution: (id, data) => api.put(`/tournaments/institutions/${id}/`, data),
  getMyInstitution: () => api.get('/tournaments/institutions/my/'),
  getInstitutionAthletes: (id) => api.get(`/tournaments/institutions/${id}/athletes/`),
  getInstitutionCoaches: (id) => api.get(`/tournaments/institutions/${id}/coaches/`),
  getAthletes: (params) => api.get('/tournaments/athletes/', { params }),
  getAthlete: (id) => api.get(`/tournaments/athletes/${id}/`),
  createAthlete: (data) => api.post('/tournaments/athletes/', data),
  updateAthlete: (id, data) => api.put(`/tournaments/athletes/${id}/`, data),
  deleteAthlete: (id) => api.delete(`/tournaments/athletes/${id}/`),
  getCoaches: (params) => api.get('/tournaments/coaches/', { params }),
  getCoach: (id) => api.get(`/tournaments/coaches/${id}/`),
  createCoach: (data) => api.post('/tournaments/coaches/', data),
  updateCoach: (id, data) => api.put(`/tournaments/coaches/${id}/`, data),
  deleteCoach: (id) => api.delete(`/tournaments/coaches/${id}/`),
  getMyAthletes: () => api.get('/tournaments/athletes/my/'),
};

export const competitionApi = {
  getRegistrations: (params) => api.get('/competitions/registrations/', { params }),
  createRegistration: (data) => api.post('/competitions/registrations/', data),
  updateRegistration: (id, data) => api.put(`/competitions/registrations/${id}/`, data),
  approveRegistration: (id) => api.patch(`/competitions/registrations/${id}/approve/`),
  rejectRegistration: (id) => api.patch(`/competitions/registrations/${id}/reject/`),
  getMyRegistrations: () => api.get('/competitions/registrations/my/'),
  getAthleteRegistrationOptions: (athleteId) => api.get(`/competitions/athlete/${athleteId}/registration-options/`),
  getAthleteEvents: (eventPk) => api.get(`/competitions/events/${eventPk}/athlete-events/`),
  createAthleteEvent: (eventPk, data) => api.post(`/competitions/events/${eventPk}/athlete-events/`, data),
  getJudgeAssignments: (eventPk) => api.get(`/competitions/events/${eventPk}/judges/`),
  createJudgeAssignment: (eventPk, data) => api.post(`/competitions/events/${eventPk}/judges/`, data),
  getMyJudgeAssignments: () => api.get('/competitions/judges/my/'),
  getResults: (params) => api.get('/competitions/results/', { params }),
  createResult: (data) => api.post('/competitions/results/', data),
  getFinalResults: (params) => api.get('/competitions/final-results/', { params }),
  createFinalResult: (data) => api.post('/competitions/final-results/', data),
  getEventResultsPublic: (eventPk) => api.get(`/competitions/events/${eventPk}/final-results/public/`),
};

export const usersApi = {
  getUsers: (params) => api.get('/auth/users/', { params }),
  createUser: (data) => api.post('/auth/users/create/', data),
  getUser: (id) => api.get(`/auth/users/${id}/`),
  updateUser: (id, data) => api.put(`/auth/users/${id}/`, data),
  deleteUser: (id) => api.delete(`/auth/users/${id}/`),
  toggleActive: (id) => api.patch(`/auth/users/${id}/toggle-active/`),
};
